kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    kubernetes.io/ingress.class: 'nginx'
spec:
  tls:
    - hosts:
        - {{ .Values.config.baseDomain }}
      secretName: admin-tls
  rules:
    - host: {{ .Values.config.baseDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: 80
